import type { Milestone } from '$lib/modules/hyvflow/types/milestone';
import type { Task } from '$lib/modules/hyvflow/types/task';
import { writable } from 'svelte/store';

export let sideleft = writable<string>('');
export let typerelation = writable<string>('');
export let taskrelationships = writable<any>([]);
export let tasklistdependencies = writable<any>([]);
export let taskcurrentrelationships = writable<any>(null);
export let checklistindexselected = writable<any>(null);
export let onTaskData = writable<Task | null>(null);
export let opendependencies = writable<boolean>(false);
export let isopendeletetask = writable<boolean>(false);
export let tasktodelete = writable<Task | null>(null);
export let milestoneInfo = writable<Milestone | null>(null);
export let istypingComment = writable<boolean>(false);
export let showReplies = writable<boolean>(false);
export let isdrag = writable<any>(false);
export let openaddtask = writable<boolean>(false);
export let currentCommentIndex = writable<number>(0);
export let remainingTime = writable<number>(0);
export let openimagencomment = writable<boolean>(false);
export let taskscounterdeleted = writable<number>(1);
export let imagenCommentURL = writable<string>('');
export let currentanimation = writable<string>('');
export let typecomponentTasks = writable<string>('principal');
export let payloadTaskModal = writable<any>(undefined);
export let myTasks = writable<Task[]>([]);
export let refreshTaskTree = writable<number>(0);
